name: Coveralls

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SAMPLES_FOLDER: "../../../../../samples"
  OUTPUT_SAMPLES_FOLDER: "../../../../../samples/out"
  OUTPUT_SINGLE_CASES_FOLDER: "../../../../../samples/out/single_cases"
  LOCAL_ENV: "false"
  DELTA: "0.00001"
  DECIMAL_PRECISION: "5"
  RUN_DWG_WRITER_SINGLE_CASES_TEST: "false"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true
    - uses: cardinalby/export-env-action@v2
      with:
        envFile: 'github.env'
    - name: Build and Test
      working-directory: src
      run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=lcov --no-build --verbosity normal ACadSharp.Tests/
    - name: Coveralls action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ github.token }}
        path-to-lcov: src/ACadSharp.Tests/TestResults/coverage.info 